/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CONTROLUSUARIO_H_RPCGEN
#define _CONTROLUSUARIO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 40
#define MAXUSUARIO 10

struct usuarios {
	char nombres[MAXNOM];
	char usuario_unicauca[MAXUSUARIO];
	int id_usuario;
	char contrasenia[MAXUSUARIO];
	char rol[MAXNOM];
};
typedef struct usuarios usuarios;

struct sesion {
	char usuario_unicauca[MAXUSUARIO];
	char contrasenia[MAXUSUARIO];
};
typedef struct sesion sesion;

#define controlUsuario 0x20000001
#define controlUsuario_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define iniciar_sesion 1
extern  sesion * iniciar_sesion_1(sesion *, CLIENT *);
extern  sesion * iniciar_sesion_1_svc(sesion *, struct svc_req *);
#define registrar 2
extern  bool_t * registrar_1(usuario *, CLIENT *);
extern  bool_t * registrar_1_svc(usuario *, struct svc_req *);
extern int controlusuario_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define iniciar_sesion 1
extern  sesion * iniciar_sesion_1();
extern  sesion * iniciar_sesion_1_svc();
#define registrar 2
extern  bool_t * registrar_1();
extern  bool_t * registrar_1_svc();
extern int controlusuario_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_usuarios (XDR *, usuarios*);
extern  bool_t xdr_sesion (XDR *, sesion*);

#else /* K&R C */
extern bool_t xdr_usuarios ();
extern bool_t xdr_sesion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CONTROLUSUARIO_H_RPCGEN */
