/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "controlAnteproyectos.h"

bool_t
xdr_proxAnteproyecto (XDR *xdrs, proxAnteproyecto *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct anteproyecto), (xdrproc_t) xdr_anteproyecto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_proxEvaluador (XDR *xdrs, proxEvaluador *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct evaluador), (xdrproc_t) xdr_evaluador))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_anteproyecto (XDR *xdrs, anteproyecto *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->modalidad, MAXMOD,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTITULO,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->codigo_anteproyecto))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->estudiante1, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->estudiante2, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->codirector, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_registro, MAXUSUARIO,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_aprovacion, MAXUSUARIO,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->concepto))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->estado))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numRevision))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->concepto);
		IXDR_PUT_LONG(buf, objp->estado);
		IXDR_PUT_LONG(buf, objp->numRevision);
		}
		 if (!xdr_proxAnteproyecto (xdrs, &objp->nodoSiguiente))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->modalidad, MAXMOD,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTITULO,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->codigo_anteproyecto))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->estudiante1, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->estudiante2, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->codirector, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_registro, MAXUSUARIO,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_aprovacion, MAXUSUARIO,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->concepto))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->estado))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numRevision))
				 return FALSE;

		} else {
		objp->concepto = IXDR_GET_LONG(buf);
		objp->estado = IXDR_GET_LONG(buf);
		objp->numRevision = IXDR_GET_LONG(buf);
		}
		 if (!xdr_proxAnteproyecto (xdrs, &objp->nodoSiguiente))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->modalidad, MAXMOD,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTITULO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->codigo_anteproyecto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->estudiante1, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->estudiante2, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codirector, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_registro, MAXUSUARIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_aprovacion, MAXUSUARIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->concepto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estado))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numRevision))
		 return FALSE;
	 if (!xdr_proxAnteproyecto (xdrs, &objp->nodoSiguiente))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_evaluador (XDR *xdrs, evaluador *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->codigo_anteproyecto, MAXMOD,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->evaluador1, MAXANT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->evaluador2, MAXANT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_modConceptoEvaluadores (XDR *xdrs, modConceptoEvaluadores *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->codigo_anteproyecto, MAXMOD,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto1, MAXCONC,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->evaluador1, MAXANT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto2, MAXCONC,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->evaluador2, MAXANT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fechaMod, MAXUSUARIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ingConcepto (XDR *xdrs, ingConcepto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoAnteproyecto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto, MAXCONC,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXUSUARIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
