/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "controlUsuario.h"

bool_t
xdr_usuarios (XDR *xdrs, usuarios *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombres, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->usuario_unicauca, MAXUSUARIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_usuario))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->contrasenia, MAXUSUARIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rol, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sesion (XDR *xdrs, sesion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->usuario_unicauca, MAXUSUARIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->contrasenia, MAXUSUARIO,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
